### ISSUE TITLE
To support Heroku-type services, honor the REDIS_URL env variable

### ISSUE THREAD

**Issue by blysik** [jimmycuadra/lita#102]
Most PaaS that supply a Redis instance, will populate the REDIS_URL env variable, which looks like so:

```
redis://redisdb:<password>@<host>:<port>/0
```

If that's defined, lita should honor it.

**Comment by blysik** [comment]
This worked for me.  

redis_url = URI.parse(ENV['REDIS_URL'] || "redis://localhost:6379")
 config.redis['host'] = redis_url.host.to_s
 config.redis['port'] = redis_url.port.to_i

**Comment by jimmycuadra** [comment]
Fortunately, it's even easier than that! http://docs.lita.io/getting-started/deployment/#heroku
