### ISSUE TITLE
Save rooms joined in and rejoin on restart

### ISSUE THREAD

**Issue by docwhat** [jimmycuadra/lita#107]
It would be nice if there was an option to have the bot save the rooms it has joined.

Then it could rejoin those rooms on restart.

Example of how this could be configured:

```
Lita.configure do |config|
  config.robot.rooms = %w( list of rooms )
  # or
  config.robot.rooms = :persist
end
```

It would make managing the bot much easier than having to change config files and restart it.

**Comment by jimmycuadra** [comment]
Closing this in favor of #116, since more discussion has been happening there. Thank you for this issue – the feature will make it in sooner rather than later!
