### ISSUE TITLE
Release date, commit date for github plugins

### ISSUE THREAD

**Issue by maxmeyer** [jimmycuadra/lita#111]
Hi @jimmycuadra,

what about adding the latest release date and/or commit date for plugins being hosted on github [on the plugin page](https://www.lita.io/plugins)?

/mm

**Comment by jimmycuadra** [comment]
Good idea. There will be a big revamp to the plugins page in the semi-near-future. There are a few things blocking it right now, but it should be getting much more useful and usable.

**Comment by maxmeyer** [comment]
Thanks for the feedback.
