### ISSUE TITLE
Getting Started: Echo Handler

### ISSUE THREAD

**Issue by rossgeesman** [jimmycuadra/lita#112]
I setup Lita according to the documentation and it appears to be running properly. I tried the Echo Handler example by generating a handler in the root folder with: `lita handler echo`.

Then I added the code from the example to lita-echo/lib/lita/handlers/echo.rb:
```
module Lita
  module Handlers
    class Echo < Handler
      route(/^echo\s+(.+)/, :echo, help: { "echo TEXT" => "Echoes back TEXT." })

      def echo(response)
        response.reply(response.matches)
      end
    end

    Lita.register_handler(Echo)
  end
end

```
After running Lita with the shell adapter configured in lita_config.rb like so: `config.robot.adapter = :shell` I get no response with stuff like:
```
Lita > lita echo foo
Lita > lita: echo foo
Lita > Lita, echo foo
Lita > echo foo
```
I've tried this in both the Lita Development Environment with Vagrant and on my OSX machine with Ruby 2.2.0 and I'm having no success. Any advice?

**Comment by jimmycuadra** [comment]
Where are you running Lita from? Inside the lita-echo directory?

**Comment by rossgeesman** [comment]
Inside the projects root folder, in my case it's just called lita.

**Comment by jimmycuadra** [comment]
To load the handler into Lita, it must be added to the Gemfile or required manually from inside lita_config.rb. If you generated the full boilerplate for your echo handler with `lita handler echo` and the "lita-echo" directory is in the root of your Lita project, then you can add this to your Gemfile:

``` ruby
gem 'lita-echo', path: 'lita-echo'
```

Generally plugins exist as separate Git repositories and are pulled into a Lita project at runtime through the Gemfile. However, if you want to load plugins from the local project so you don't have to manage a separate Git repo, it's common to just add them in plain Ruby files inside your Lita project and require them manually from lita_config.rb. If you had a directory layout like this:

```
.
|– lita
|

**Comment by rossgeesman** [comment]
Thanks so much. I included the gem and specified the path and it works fine.
