### ISSUE TITLE
Remember Rooms in Redis

### ISSUE THREAD

**Issue by natesholland** [jimmycuadra/lita#116]
We are trying to figure out how to get Lita to remember the rooms it has joined after a reboot. I'm thinking this may be pretty helpful for other people as well.

We were thinking Lita would have a list of rooms in redis so that when lita restarted it could look at that list and redis and rejoin the rooms it was in before it got shut down. On the join and part commands this list would be updated so the redis list stays up to date.

Does this sound like a helpful feature? I could try and do this right and open a PR if other people think this is helpful.

**Comment by jimmycuadra** [comment]
This has been requested a few times, so I think it's a feature that needs to be introduced in one way or another. The open question for me is what will become of the configuration in lita_config.rb that currently handles this. Will it become a no-op? Will it populate this list in Redis initially but have no effect if the list already exists? I don't want to confuse users with multiple ways to do the same thing that are subtly different.

Imagine the situation where you have rooms A, B, and C in the config file. Then you launch Lita, and send it the part command to leave room C. This is then persisted to Redis. What happens the next time you start Lita? The config file says it should join room C, but you've asked it not to at runtime since then. What is the source of truth?

**Comment by natesholland** [comment]
I'm honestly not sure about how we should handle that. I can describe what my first stab at it looked like and how it works, then we can discuss how it should work.

```ruby
module Lita
  # A namespace to hold all subclasses of {Handler}.
  module Handlers
    # Allows administrators to make Lita join and part from rooms.
    # @since 3.0.0
    class Room < Handler

      on :connected, :join_rooms

      route(/^join\s+(.+)$/i, :join, command: true, help: {
        t("help.join_key") => t("help.join_value")
      })

      route(/^part\s+(.+)$/i, :part, command: true, help: {
        t("help.part_key") => t("help.part_value")
      })

      # Joins the room with the specified ID.
      # @param response [Lita::Response] The response object.
      # @return [void]
      def join(response)
        Lita.redis.sadd('room_list', response.args[0])
        robot.join(response.args[0])
      end

      # Parts from the room with the specified ID.
      # @param response [Lita::Response] The response object.
      # @return [void]
      def part(response)
        Lita.redis.srem('room_list', response.args[0])
        robot.part(response.args[0])
      end

      def join_rooms(_payload)
        rooms = Lita.redis.smembers('room_list')
        rooms.each do |room|
          begin
            robot.join(room)
          rescue
          end
        end
      end

    end
  end
end
```

This was my first implementation. So with this implementation it would load all the rooms in the config and then all the rooms that lita was connected to when it was shut down. However in my implementation we don't use the list in lita_config because we invite the bot to a room once and then it will stay there over restarts. So we can worry about how that list will work but I suspect once we implement this most people will just invite lita into whatever rooms they want and then stop using the list in lita_config.

**Comment by jimmycuadra** [comment]
I think you're right that there isn't a reason to have this in the config file once it's being managed with runtime commands, but that's kind of backwards incompatible. The other tricky thing is that these configuration attributes are actually handled by each adapter, not Lita itself, so there isn't an easy way to deprecate it and provide an upgrade path in one fell swoop.

**Comment by natesholland** [comment]
Agreed, I don't really know a great way to migrate forward. I wouldn't be upset if whenever Lita reboots we do an or with the list in redis and the list in the lita_config. I know that would work for my use case but obviously I can't speak for anyone.

**Comment by jimmycuadra** [comment]
What I'm probably going to do is add this as a core feature in the near future, and provide it as an official way to do what the existing adapters have each been implementing themselves. Then each adapter is free to use it or not, with the intent being that they probably should, and provide their own upgrade paths for doing this via the config file.

**Comment by natesholland** [comment]
Sounds good, let me know if I can help.
