### ISSUE TITLE
Connecting to persisted rooms won't recognize new rooms

### ISSUE THREAD

**Issue by natesholland** [jimmycuadra/lita#124]
Currently there is an issue in lita where it won't add a new room to persisted rooms because it doesn't know about that room yet. Basically what happens is we call `robot.join(room)` and this happens:

```ruby
    def join(room)
      room_object = find_room(room)

      if room_object
        Lita.redis.sadd("persisted_rooms", room_object.id)
        adapter.join(room_object.id)
      else
        adapter.join(room)
      end
    end
```

This calls `find_room` which ends up calling 'Room.fuzzy_find(room_or_identifier)' which calls these two methods:

```ruby
      def find_by_id(id)
        metadata = redis.hgetall("id:#{id}")
        new(id, metadata) if metadata.key?("name")
      end

      def find_by_name(name)
        id = redis.get("name:#{name}")
        find_by_id(id) if id
      end
```

The problem is that if the room you are trying to join is not in redis then this will say that the room object can't be found and therefore `find_room` will return nil and therefore Lita will not put that room into persisted rooms. This breaks the new persisted rooms functionality as far as I can tell*.

To fix this I think we may need to add a slight modification to `room.find_by_name` or `room.find_by_id`, alternatively we could blindly add those strings into redis and then have the adapter rescue on a failed join. But I wanted to open this up for discussion so we could get it fixed.

(*Note, I am testing all of this with lita-hipchat)

**Comment by jimmycuadra** [comment]
I'd say this is a lita-hipchat issue. Room objects should be created as soon as the adapter learns about them (when it first connects, looking at the roster, etc.)
