### ISSUE TITLE
Make routes to behave like functions

### ISSUE THREAD

**Issue by braiden-vasco** [jimmycuadra/lita#125]
I want to make plugin which can store the result of command in variable for future use. This is how it should look like (example with `lita-key-value` plugin):
```
You: lita kv get foo
Lita: foo bar
You: $FOO=kv get foo
You: lita kv set foo2 $FOO
Lita: Set foo2 to foo bar.
```
This plugin will be a handler, cause it handles routes with `$VAR=` and other plugins should not depend on it. Now I can trigger robot to handle other route with the following code:
```ruby
message = Message.new(robot, 'kv get foo', response.message.source)
message.command!
robot.receive(message)
```
But I can't get Lita's reply to this command to store it in variable.

What I want is to make routes to behave like functions, for example:
```ruby
foo = call_command('kv get foo')
```

I can write specs and implement this, but I need some help to make it in the best way, so let's talk about this.

**Comment by jimmycuadra** [comment]
Interesting use case. What you're describing is basically the equivalent of command substitution in shell scripts, e.g. `echo $(some_command_that_outputs_text)`.

My original design for handlers was for them to be as unaware of each other as possible to avoid any accidental side effects or dependencies. The event system is also provided for asynchronous, fire-and-forget communication between handlers if absolutely necessary, but that is not really helpful in this case.

There isn't really a concept of "return value" for a chat route since it's a command method (see [Command-query separation](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation)) and may have any number of side effects. It's possible for a chat route to send zero messages, one message, many messages to the same target, messages to different targets, etc. How would such actions be represented in a return value?

**Comment by braiden-vasco** [comment]
Yes, this was inspired by substitution in shell scripts.

I really like the idea of asynchrony. So I suggest to use promises instead of "return value". While command is being handled, callback is called every time as the command replies with message. Here is an example of route which calls some command and gets it's "return value":
```ruby
s = ''
call_command('command which replies multiple times') do |message|
  s << message.body
end
# At this point execution of called route is finished
# and we have it's full output in `s`
```

**Comment by jimmycuadra** [comment]
That seems like too narrow an API to cover the myriad of things the chat route callback might do. It would also mean that `call_command`'s callback would either block the execution of the chat route callback, or it'd have to be executed in another thread, which is a pretty big can of worms. I'm not sure the added complexity is justified here.

Before talking about possible implementation more, it's probably worth talking more about the use case. How are you imagining this type of command substitution would be used in the real world? Perhaps there is another approach to the problem.

**Comment by braiden-vasco** [comment]
No needs to cover all things. Let's follow the Unix way and handle only `response.reply(text)`. Our handler will interact with command in the same way as user - through text interface. I believe that if text information is enough for the user, it will be enough for our handler too.

`call_command`'s callback will take execution at `response.reply(text)`. I don't think this is problem, cause user originally calls comprehensive command and he's interested in it's result, not in result of nested command. Because of this author of handler is interested to execute fast, so he won't place huge calculations in callback.

Also `call_command` can be executed asynchronously, but without threads as in Node.js: at first nested command is executed completely, then `call_command`'s callbacks are executed for each message keeping the order.

***

The reason to implement this (not simple, I admit) feature is to make Lita a powerful tool, not only interface to run Ruby code from chats. Sometimes I want the data from one handler to be submitted to other handler, but I don't want to copy it with mouse.

**Comment by jimmycuadra** [comment]
Thanks for the additional info. :} I will spend some time thinking about it.

**Comment by jimmycuadra** [comment]
I think the complexity added to the system would not be worth it for this feature. Thank you for the idea and for discussing it with me!

**Comment by braiden-vasco** [comment]
I have found that `response.reply` in handler's callback always turns into `response.message.reply`. Please correct me if I'm wrong. I have created class `Channel` which inherits `Lita::Message`. It adds own `#reply` method which calls my code instead of sending messages to robot. Now I can get handler's reply to message when I send instance of `Channel` to robot as message.

I have implemented this as plugin. It was a bit tricky - plugin includes both handler and extension. Extension is needed to disallow routing to other handlers - my handler triggers modified commands by itself. If you are interested please look at https://github.com/braiden-vasco/lita-substitution

**Comment by jimmycuadra** [comment]
Very cool! Thank you for sharing.
