### ISSUE TITLE
Message helpers

### ISSUE THREAD

**Issue by brodock** [jimmycuadra/lita#132]
This can be used to build adapter specific features in a generic way.

I don't know a full list of adapters/features that can benefit for it right know, but I have one item to the list:
Mention links.

In slack, if I type:
```
@brodock: see this
```

The mentioned name will be a link. In fact what is sent is ```<@UNIQUEID>```.
It would be good to have something to use with templates that can generate it easier like 

```
<%= mention(@user)>: see this
```

Where ```@user``` is a Lita::User

**Comment by jimmycuadra** [comment]
I quite like this idea. There could be an API that allowed adapters to register an arbitrary Ruby module which would get included in the template context for that adapter.

**Comment by jimmycuadra** [comment]
Added in e30b01f.
