### ISSUE TITLE
Can't use neither t() nor translate() in templates

### ISSUE THREAD

**Issue by brodock** [jimmycuadra/lita#135]
I was trying to make some alternative changes to one of my plugins, to make use of slack mention markup for users and channels, until something official from https://github.com/jimmycuadra/lita/issues/132 is implemented.

I'm using I18n with some interpolated strings (room and mention), which I want to invoke differently for slack adapter.

Because of this specific need, I can't call translate inside the handler class, but have to call it inside the .erb file.

**Comment by jimmycuadra** [comment]
The handler's `translate` method is just a convenience method. For now you can just call `I18n.translate` directly as the convenience method does:

``` ruby
I18n.translate("lita.handlers.my_handler_namespace.some_translation_key", foo: 'bar')
```
