### ISSUE TITLE
Lita 4.6.0 change in config load?

### ISSUE THREAD

**Issue by miketheman** [jimmycuadra/lita#139]
Hi @jimmycuadra !
Been working on lita-jenkins recently, and the recent release of 4.6.0 seems to have changed something in the way we were testing a handler's method.

Here's our current thread:
https://github.com/daniely/lita-jenkins/pull/15#issuecomment-136011500

The commit in question is changing the config method to the newer syntax, and I couldn't find any associated change with the referenced line from the error:

    lita/gems/lita-4.6.0/lib/lita/handler/common.rb:63:in `initialize'

Can you advise as to why this won't work any longer, and maybe offer a better way to instantiate the test?

**Comment by miketheman** [comment]
Would this commit 162d414ce9769875af3c171facc244680a95594e have something to do with it?

**Comment by jimmycuadra** [comment]
I will respond on daniely/lita-jenkins#15! Closing as this is not a Lita issue.

**Comment by miketheman** [comment]
Thanks!
