### ISSUE TITLE
RSpec suite changes break existing handler tests

### ISSUE THREAD

**Issue by tristaneuan** [jimmycuadra/lita#142]
Tests that were previously passing in lita-enhance and lita-github using lita v4.4.3 are now breaking using lita v4.6.1. For example:

https://github.com/PagerDuty/lita-enhance/blob/master/spec/lita/handlers/enhance_spec.rb#L25
```
  1) Lita::Handlers::Enhance should be possible to force a refresh of the index
     Failure/Error: expect(subject).to receive(:lock_and_refresh_index)
       (#<Lita::Handlers::Enhance:0x007ffbb39612f0>).lock_and_refresh_index(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
     # ./spec/lita/handlers/enhance_spec.rb:25:in `block (2 levels) in <top (required)>'
```

In this particular case, adding the deleted line shown below back into the RSpec setup causes the test to pass again. 
https://github.com/jimmycuadra/lita/compare/v4.4.3...v4.6.1#diff-b6b17e0233f2744d6404b46c35cc020fL73

The following changes also had to be made to lita-github in order to get tests that worked previously to pass with lita v4.6.1:
https://github.com/PagerDuty/lita-github/pull/36

**Comment by jimmycuadra** [comment]
This is a tricky one. I definitely didn't intend to break anyone's programs, but having that line in the RSpec setup was definitely a bug. It would cause every new handler allocation to return whatever the first instance created was.

I think the way to test a handler that won't rely on that behavior is to make assertions about side effects of a handler's methods getting called, e.g. messages sent to the "replies" array, code run as a result of an event being triggered, etc. Is that sufficient or is there something else that would help?
