### ISSUE TITLE
Enable rich (html) messages

### ISSUE THREAD

**Issue by apsoto** [jimmycuadra/lita#66]
sparked from the conversation at jimmycuadra/lita-hipchat#7.

To allow plugins to provide adapter specific rich formatted messages we can borrow the Rails pattern for view templates.

The plugin can provide templates that follow the pattern: HANDLER.ROUTE.ADAPTER.erb, where:

HANDLER = registered handler class name
ROUTE = the method symbol passed to #route
ADAPTER = the adapter name (hipchat, slack, shell, etc)

For example, the lita-jira plugin can provide hipchat and slack specific templates like so:
```
jira.issue_details.hipchat.erb
jira.issue_details.slack.erb
```
If the argument sent to `Response#reply` is a hash, it's the context variables to use in a template, otherwise fall back to old behavior which is a text message

If the adapter being used doesn't have a template, then the hash should provide a fallback message string which would be the same message string that's passed now.

This would allow plugin authors to provide rich response templates, but existing ones continue to work sending plain text.

**Comment by jimmycuadra** [comment]
This is released in Lita 4.2! Thanks for helping figure out how to get this feature in!

http://localhost:4567/plugin-authoring/handlers/#templates

**Comment by apsoto** [comment]
great, can't wait to try it out.

**Comment by dieterdemeyer** [comment]
I'm trying this out using the slack adapter but can't seem to get this working..
Should it now be possible to handle for example bold text, bullet points and href elements in an ERB template ?
I'm not really sure what I'm doing wrong with my example:

```
<b><%= @members.length %></b> members in GitHub Team <b><%= @team %></b><br>
<% @members.each do |member| %>
&bull; <%= member %><br>
<% end %>
```
Any tips would be appreciated...

**Comment by jimmycuadra** [comment]
Slack doesn't use HTML in messages, it uses a Markdown-style format: https://slack.zendesk.com/hc/en-us/articles/202288908-Formatting-your-messages

**Comment by dieterdemeyer** [comment]
I feel quite stupid now...
I tried it and this works for most items, except the URL handling...
I'm using the following code in my .erb file:
```
*GitHub Org Pull Requests:*
<% @github_open_issues.each do |repo_name, issues| %>
<% issues.each do |issue| %>
• <%= repo_name %>: <<%= issue.html_url %>|pull request #<%= issue.number %>> - <%= issue.title %> - by <<%= issue.user.html_url %>|<%= issue.user.login %>>
<% end %>
<% end %>
```
Any suggestions on what I'm doing wrong ?

**Comment by jimmycuadra** [comment]
What is the expected output and what are you seeing instead?

**Comment by dieterdemeyer** [comment]
The output now is:

• puppet-alternatives: <https://github.com/cegeka/puppet-alternatives/pull/1|pull request #1> - fix: insync function comparing current and should items - by <https://github.com/vladnazarenko|vladnazarenko>

But I would like to see the following:

• puppet-alternatives: [pull request #1](https://github.com/cegeka/puppet-alternatives/pull/1) - fix: insync function comparing current and should items - by [vladnazarenko](https://github.com/vladnazarenko)

I think I'm using the correct syntax for links in Slack but any help would be appreciated.

**Comment by jimmycuadra** [comment]
Would you mind opening a separate issue on lita-slack? I don't wanna lose track of this!

**Comment by dieterdemeyer** [comment]
No problem.
Issue submitted at https://github.com/kenjij/lita-slack/issues/36
