### ISSUE TITLE
http.get in custom "handler" plugin fails for 301 (redirects) & self-signed certificates

### ISSUE THREAD

**Issue by dtogias** [jimmycuadra/lita#75]
I'm using lita-jenkins plugin and i noticed that http.get fails if jenkins.url redirects (301) to another page or we use https with a self signed certificate. A possible solution for the https would be to add:
```
ssl: { verify: false }
```
to default_faraday_options in lita/lib/lita/handler/common.rb.

**Comment by esigler** [comment]
I would not want to see SSL verification disabled by default, that sounds like both a bad user experience and concerning from a security perspective.  It seems like a better option would be to either have this as an option that could be enabled globally, or perhaps better handled on a per-plugin basis?

I suspect a lot of Jenkins servers have self-signed certificates, so updating https://github.com/daniely/lita-jenkins/blob/master/lib/lita/handlers/jenkins.rb to pass along this option in HTTP requests (again, with a toggle to enable/disable) could put the fix closer to where it's most useful?

**Comment by dtogias** [comment]
I'm not sure about this but the "http" object is passed from lita to each handler. I don't think a plugin can change the ssl verification of an http connection.

**Comment by jimmycuadra** [comment]
The first argument to `http` is a hash of options that get passed along to Faraday, so you can configure it as you wish.
