### ISSUE TITLE
before_run hook runs too early

### ISSUE THREAD

**Issue by romanbsd** [jimmycuadra/lita#76]
It runs before the configuration is loaded. I'd expect it to run after the configuration is loaded, just before Robot.new.run.
I can create a pull request if it makes sense.

P.S.  Also, it would be nice if it could optionally accept a block.

**Comment by jimmycuadra** [comment]
I wouldn't want to change the behavior of the existing `:before_run` hook, but I'd certainly accept a PR that adds a new hook after the configuration is finalized and before the robot is run. Perhaps `:configuration_finalized`?
