### ISSUE TITLE
If doing long handler messages send once when job is done

### ISSUE THREAD

**Issue by stamm** [jimmycuadra/lita#78]
If I write something like this:
```ruby
route /^test$/ do |response|
  response.reply("start")
  sleep 2
  response.reply("end")
end
```
All messages appear at same time. It's strange behavior.

**Comment by jimmycuadra** [comment]
Which adapter are you using?

**Comment by jimmycuadra** [comment]
I'm guessing you are using the Slack adapter, in which case this is the same issue as #77. Let's continue the conversation there.
