### ISSUE TITLE
Make the user backend configurable?

### ISSUE THREAD

**Issue by ph** [jimmycuadra/lita#87]
The current implementation require the use of Redis to store the user data.
We are already running a few Elasticsearch clusters and we would like to use them to store our data.

Would you accept a patch to make the user backend configurable? cc @jordansissel

**Comment by jimmycuadra** [comment]
This is a good question. Part of the original design of Lita was to couple it pretty closely with Redis so it could take advantage of all of Redis's features, as opposed to the way Hubot is decoupled to its backend but can only assume the lowest common denominator of features. While the user and authentication components of Lita might not necessarily require Redis-specific features, but a lot of code, including user-developed plugins, will assume a Redis instance to be available, so I'm not sure it's feasible to remove it as a dependency.

Are there Elasticsearch-specific features you'd want to use, or is your motivation more about not wanting to run a Redis instance when you already have a data store that could fulfill the same purpose?

**Comment by ph** [comment]
full disclosure here, I work for Elastic the company behind elasticsearch and we are currently using lita as a part of our tools and since we are developing more components to our bot it would make sense for us to leverage our existing ES infrastructure.

A few ideas that come to my mind is to use an index to save bot errors or some messages to an existing elasticsearch search cluster and use the bot to query that information.

**Comment by jimmycuadra** [comment]
I think at this point I'm not ready to make Redis an optional/removable component. However, I do want Lita to be extensible enough for people to build features like this via extension plugins. Take a look at the extension system here: http://docs.lita.io/plugin-authoring/extensions/. If there are new hooks that could be added that would help facilitate an Elasticsearch extension, I'd be happy to include them, either as PRs or just issues describing what's desired.
