### ISSUE TITLE
Figure out what room response is coming from

### ISSUE THREAD

**Issue by natesholland** [jimmycuadra/lita#90]
This may be possible but I've been digging through the code for at least 30 minutes and I can't find it. I would like to be able to call `response.room` in a handler and figure out what room that response is coming from. I'm going to be using this with the hipchat adapter but I think it would be nice if this also worked with the shell adapter and it said the room was simply "shell" or some other default. The hubot equivalent of this would be calling `msg.message.room`

**Comment by natesholland** [comment]
Ok I just realized that this can be found in `response.message.source.room` but if you are using the shell adapter this is set to nil

**Comment by jimmycuadra** [comment]
Continued in #91.
