### ISSUE TITLE
Installation instructions have a dead link

### ISSUE THREAD

**Issue by rpherbig** [jimmycuadra/lita#93]
http://docs.lita.io/getting-started/installation/ has a section on using Vagrant. Step 2 of that section has a dead link to VirtualBox (http://docs.lita.io/getting-started/installation/VirtualBox).

**Comment by jimmycuadra** [comment]
Fixed in [litaio/docs.lita.io/cfb5de5](https://github.com/litaio/docs.lita.io/commit/cfb5de504f3e307c859887cf2f7bea9d18b4ba10). Thanks!
