### ISSUE TITLE
Add option to require a command be used in an open channel.

### ISSUE THREAD

**Issue by MrJoy** [jimmycuadra/lita#96]
Since much of the goal of chatops is to coalesce information about the operation of the system into one easily reviewed place, being able to define a command such that it can't be used via a PM to Lita could be helpful for helping to make good habits the path of least resistance.

**Comment by jimmycuadra** [comment]
I'd be open to this. Any ideas what the option to enforce this for a chat route should be called?

**Comment by MrJoy** [comment]
I suppose it depends on how the feature would work.  Would it be desirable/worthwhile to put constraints in terms of specific channels -- or just kind?

An option called `:allow_in` that takes a list with strings being arbitrary channel names, and symbols of `:public` and `:direct` to indicate "any public channel" or "direct messaging" might be a good option?

**Comment by jimmycuadra** [comment]
I think restricting commands to specific rooms is desirable. I think that has even been requested before. Requiring a room but not specifying which ones seems of less value. After all, you could just create an empty room to circumvent that restriction.

It's a little unfortunate that I already used the generic name "restrict_to" to restrict a route based on authorization groups. The same name could easily apply to a room restriction. Once I thought about that, I considered having the restrict_to option accept more complicated values, such as a hash like `{ auth_groups: [:foo_admins], rooms: ["#my_channel"] }`, or even having a single array that allows a mixture of some sort of auth group object and room object. I think that all starts to get too confusing, though. All the options for the route method are getting pretty heavy as it is. I'll keep thinking on it.

**Comment by MrJoy** [comment]
I agree that it's *less* useful, but it's not always *useless*.  For example, I might have all public channels logged/searchable but keep private channels unlogged.  It's out-of-band but it's relatively obvious on services where your channel list is small (Slack, Hipchat) when someone does that -- and you still get history tracking.  That said, I'm not married to that particular detail.

At some point, allowing a `proc` as a value in either `auth_groups` or `rooms` arrays may be useful for allowing people to do bizarre one-off things without contorting things too much.  I wouldn't worry too much about intertwingling auth groups and rooms right now unless there's a specific use-case in mind that you've got.

**Comment by jimmycuadra** [comment]
I don't know why I didn't think of this before, but this can already be achieved with an extension using the `:validate_route` hook. Take a look at [lita-confirmation](https://github.com/jimmycuadra/lita-confirmation) for an example of using that hook.
